language: bash

before_script:
  - curl -s https://packagecloud.io/install/repositories/varnishcache/varnish5/script.deb.sh | sudo bash
  - sudo apt install varnish -y

script:
  - pwd
  - sudo varnishd -C -f /home/travis/build/pad92/varnish/production.vcl
  - sudo varnishd -C -f ./production.vcl
