language: bash

before_script:
  - curl -s https://packagecloud.io/install/repositories/varnishcache/varnish5/script.deb.sh | sudo bash
  - sudo apt install varnish -y

script:
  - find / -type f -name 'varnishd'
  - find / -type f -name 'production.vcl'
  - varnishd -C -f ./production.vcl
