language: bash

before_script:
  - curl -s https://packagecloud.io/install/repositories/varnishcache/varnish5/script.deb.sh | sudo bash
  - sudo apt install varnish -y

script:
  - sudo cp -r . /etc/varnish/
  - sudo cp -y /etc/varnish/production.vcl /etc/varnish/default.vcl
  - sudo service varnish restart
